@startuml

actor Veterinarian
participant "PetController" as Controller
participant "PetManagement" as Service
participant "PetRepository" as Repository
participant "ApplicationEventsPublisher" as Publisher


Veterinarian -> Controller: POST /owners/{ownerId}/pets/new
Controller -> Service: getPetByName()
activate Controller
activate Service
Service -> Repository: findPetByName()
activate Repository
Repository --> Service: pet
deactivate Repository
Service --> Controller: pet
alt pet == null
    Controller -> Service: save(pet)
    Service -> Publisher: events.publishEvent(new AddPetEvent())
    Service -> Repository: save(pet)
    Service --> Controller: success
    deactivate Service
    Controller --> Veterinarian: success
else pet != null
    Controller --> Veterinarian: error: Pet already exists
    deactivate Controller
end


@enduml
