@startuml

actor Veterinarian
participant "OwnerController" as Controller
participant "OwnerManagement" as Service
participant "OwnerRepository" as Repository

Veterinarian -> Controller: GET /owners
activate Controller
Controller -> Service: findByLastName(lastName)
activate Service
Service -> Repository: findByLastName(lastName))
activate Repository
Repository --> Service: Page<Owner>
deactivate Repository
Service --> Controller: PageImpl<>(ownerDTOList)
deactivate Service
Controller -> Veterinarian:return "owners/ownersList"
deactivate Controller


@enduml
